function out1 = rbt_state_fcn(in1,in2)
%RBT_STATE_FCN
%    OUT1 = RBT_STATE_FCN(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    31-Dec-2022 01:36:40

dtheta_com = in1(6,:);
dx_com = in1(4,:);
dz_com = in1(5,:);
fx1 = in2(1,:);
fx2 = in2(3,:);
fz1 = in2(2,:);
fz2 = in2(4,:);
x_com = in1(1,:);
z_com = in1(2,:);
out1 = [dx_com;dz_com;dtheta_com;fx1+fx2;fz1+fz2-9.81e+2./1.0e+2;fx1.*z_com.*-2.0-fx2.*z_com.*2.0+fz1.*(x_com-2.0./5.0).*2.0+fz2.*(x_com+2.0./5.0).*2.0];
