function [A,B] = rbt_state_jacobian_fcn(in1,in2)
%RBT_STATE_JACOBIAN_FCN
%    [A,B] = RBT_STATE_JACOBIAN_FCN(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    31-Dec-2022 01:36:40

fx1 = in2(1,:);
fx2 = in2(3,:);
fz1 = in2(2,:);
fz2 = in2(4,:);
x_com = in1(1,:);
z_com = in1(2,:);
A = reshape([0.0,0.0,0.0,0.0,0.0,fz1.*2.0+fz2.*2.0,0.0,0.0,0.0,0.0,0.0,fx1.*-2.0-fx2.*2.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0],[6,6]);
if nargout > 1
    t2 = x_com.*2.0;
    t3 = z_com.*2.0;
    t4 = -t3;
    B = reshape([0.0,0.0,0.0,1.0,0.0,t4,0.0,0.0,0.0,0.0,1.0,t2-4.0./5.0,0.0,0.0,0.0,1.0,0.0,t4,0.0,0.0,0.0,0.0,1.0,t2+4.0./5.0],[6,4]);
end
